# Škola algebry v přírodě config

title: Škola v přírodě Katedry Algebry
email: skolavprirode@karlin.mff.cuni.cz
description: >- # this means to ignore newlines until "baseurl:"
  Škola v přírodě.
baseurl: "/~skolavprirode/" # the subpath of your site, e.g. /blog
url: "https://www.karlin.mff.cuni.cz" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  archive:
    output: false
    directory: "_archiv"


jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - .vendor/
  - Makefile
